state:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
position:
  joint1:
    joint: joint1
    type: "position_controllers/JointPositionController"
    pid: {p: 1,  d: 0, i: 0.1, i_clamp: 1}